### PR TITLE
support kafka-clients version 3+

### PR DESCRIPTION
**Pull request by averkhovtsev-xm**
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-java-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/main/CODE_OF_CONDUCT.md)._

### Overview
Support kafka-clients version 3.0.0+
This is basically a copy-paste of kafka-clients-metrics-0.10.0.0 instrumentation module.

### Related Github Issue
https://github.com/newrelic/newrelic-java-agent/issues/711

### Testing
The agent includes a suite of tests which should be used to
verify your changes don't break existing functionality. These tests will run with
Github Actions when a pull request is made. More details on running the tests locally can be found
[here](https://github.com/newrelic/newrelic-java-agent/blob/main/CONTRIBUTING.md),

### Checks

[+] Are your contributions backwards compatible with relevant frameworks and APIs?
[-] Does your code contain any breaking changes? Please describe. 
[-] Does your code introduce any new dependencies? Please describe.

### CODE REVIEW

**Comment by meiao** [comment]
Resolves #711

**Comment by meiao** [comment]
@averkhovtsev-xm we're going to start working on merging this to our main branch.
Though we need you to sign the CLA before we can accept your submission.

**Comment by averkhovtsev-xm** [comment]
@meiao i've signed the CLA multiple times but it is still pending. what am I doing wrong?

**Comment by meiao** [comment]
@averkhovtsev-xm probably the email you used for your commit does not match the email in Github. There is a link in the CLAassistant message where you can add the email.

**Comment by averkhovtsev-xm** [comment]
@meiao I did find the link you were talking about. 
I've updated my primary github email to the one used in the commits and did a dummy commit to rerun the cla check. seems to be ok now.

**Comment by meiao** [comment]
Some tests will not pass because it is from a forked repo. Don't worry about it since I will be taking a look at the PR and adding some tests.

**Review by meiao — APPROVED** [review]

**Comment by averkhovtsev-xm** [comment]
hello @meiao , thanks for merging the MR. do you know when the change is going to be released?

**Comment by meiao** [comment]
The next release is scheduled to late June, early July.

**Pull request merged**
