### PR TITLE
Tests for picnic caffeine pr

### PR DESCRIPTION
**Pull request by tbradellis**
Using this pr to run tests for the @Stephan202 's pr.

 https://github.com/newrelic/newrelic-java-agent/pull/572

>By default Caffeine uses ForkJoinPool.commonPool(). When running Java 17, usage of ForkJoinPool early in the agent's life cycle may trigger an initialization failure which causes the pool to become non-functional. This may produce out-of-memory errors as well as functional errors in the instrumented application. See #558 for details.

>Note: this PR updates only caches for which some cleanup/expiry policy exists, as (IIUC) instances created using "just" Caffeine.newBuilder().build(someLoader) don't use the configured executor anyway. If I got that wrong, please let me know and I'll update also the remaining usages. (And if I got it right, please double-check that I didn't miss any.)

Related:
https://github.com/newrelic/newrelic-java-agent/issues/558

### CODE REVIEW

**Comment by tbradellis** [comment]
I expect some false failures for now as we have an issue with the last Monix commit. More scala related build issues.  😞  
We have someone getting that sorted.

**Comment by Stephan202** [comment]
Cross-linking PRs for the benefit of future readers: #572.

**Comment by tbradellis** [comment]
I haven't had time to investigate this yet, but there are some interesting actual failures now.

## test failures
<details><summary>error</summary>
<p>



```java
Error: Exception in thread "Thread-11" Exception in thread "Thread-14" Exception in thread "Thread-15" Exception in thread "Thread-12" Exception in thread "Thread-10" java.lang.ClassCircularityError: java/util/concurrent/ThreadLocalRandom
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.StripedBuffer.expandOrRetry(StripedBuffer.java:209)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.StripedBuffer.offer(StripedBuffer.java:149)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:1159)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:2048)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.putIfAbsent(BoundedLocalCache.java:1994)
	at com.newrelic.weave.weavepackage.WeavePackageManager.getOptimizedWeavePackages(WeavePackageManager.java:606)
	at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:271)
	at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:261)
	at com.newrelic.agent.instrumentation.weaver.ClassWeaverService.newClassMatchVisitor(ClassWeaverService.java:455)
	at com.newrelic.agent.instrumentation.context.InstrumentationContext.match(InstrumentationContext.java:259)
	at com.newrelic.agent.instrumentation.context.InstrumentationContextClassMatcherHelper.isMatch(InstrumentationContextClassMatcherHelper.java:45)
	at com.newrelic.agent.instrumentation.context.ClassesMatcher$1.run(ClassesMatcher.java:55)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassCircularityError: java/util/concurrent/ThreadLocalRandom
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.StripedBuffer.expandOrRetry(StripedBuffer.java:209)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.StripedBuffer.offer(StripedBuffer.java:149)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:1159)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:2048)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.putIfAbsent(BoundedLocalCache.java:1994)
	at com.newrelic.weave.weavepackage.WeavePackageManager.getOptimizedWeavePackages(WeavePackageManager.java:606)
	at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:271)
	at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:261)
	at com.newrelic.agent.instrumentation.weaver.ClassWeaverService.newClassMatchVisitor(ClassWeaverService.java:455)
	at com.newrelic.agent.instrumentation.context.InstrumentationContext.match(InstrumentationContext.java:259)
	at com.newrelic.agent.instrumentation.context.InstrumentationContextClassMatcherHelper.isMatch(InstrumentationContextClassMatcherHelper.java:45)
	at com.newrelic.agent.instrumentation.context.ClassesMatcher$1.run(ClassesMatcher.java:55)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassCircularityError: java/util/concurrent/ThreadLocalRandom
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.StripedBuffer.expandOrRetry(StripedBuffer.java:209)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.StripedBuffer.offer(StripedBuffer.java:149)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:1159)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:2048)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.putIfAbsent(BoundedLocalCache.java:1994)
	at com.newrelic.weave.weavepackage.WeavePackageManager.getOptimizedWeavePackages(WeavePackageManager.java:606)
	at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:271)
	at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:261)
	at com.newrelic.agent.instrumentation.weaver.ClassWeaverService.newClassMatchVisitor(ClassWeaverService.java:455)
	at com.newrelic.agent.instrumentation.context.InstrumentationContext.match(InstrumentationContext.java:259)
	at com.newrelic.agent.instrumentation.context.InstrumentationContextClassMatcherHelper.isMatch(InstrumentationContextClassMatcherHelper.java:45)
	at com.newrelic.agent.instrumentation.context.ClassesMatcher$1.run(ClassesMatcher.java:55)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassCircularityError: java/util/concurrent/ThreadLocalRandom
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.StripedBuffer.expandOrRetry(StripedBuffer.java:209)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.StripedBuffer.offer(StripedBuffer.java:149)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:1159)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:2048)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.putIfAbsent(BoundedLocalCache.java:1994)
	at com.newrelic.weave.weavepackage.WeavePackageManager.getOptimizedWeavePackages(WeavePackageManager.java:606)
	at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:271)
	at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:261)
	at com.newrelic.agent.instrumentation.weaver.ClassWeaverService.newClassMatchVisitor(ClassWeaverService.java:455)
	at com.newrelic.agent.instrumentation.context.InstrumentationContext.match(InstrumentationContext.java:259)
	at com.newrelic.agent.instrumentation.context.InstrumentationContextClassMatcherHelper.isMatch(InstrumentationContextClassMatcherHelper.java:45)
	at com.newrelic.agent.instrumentation.context.ClassesMatcher$1.run(ClassesMatcher.java:55)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassCircularityError: java/util/concurrent/ThreadLocalRandom
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.StripedBuffer.expandOrRetry(StripedBuffer.java:209)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.StripedBuffer.offer(StripedBuffer.java:149)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:1159)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:2048)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.putIfAbsent(BoundedLocalCache.java:1994)
	at com.newrelic.weave.weavepackage.WeavePackageManager.getOptimizedWeavePackages(WeavePackageManager.java:606)
	at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:271)
	at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:261)
	at com.newrelic.agent.instrumentation.weaver.ClassWeaverService.newClassMatchVisitor(ClassWeaverService.java:455)
	at com.newrelic.agent.instrumentation.context.InstrumentationContext.match(InstrumentationContext.java:259)
	at com.newrelic.agent.instrumentation.context.InstrumentationContextClassMatcherHelper.isMatch(InstrumentationContextClassMatcherHelper.java:45)
	at com.newrelic.agent.instrumentation.context.ClassesMatcher$1.run(ClassesMatcher.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

</p>
</details>

**Comment by tbradellis** [comment]
@Stephan202 All tests are passing here. Do you prefer to update your original PR or just have us merge from here? Either works for me.

**Comment by tbradellis** [comment]
Actually, I'm still hitting this:


##  java.lang.ClassCircularityError: java/util/concurrent/ThreadLocalRandom
<details><summary>error</summary>
<p>



```java
Error: Exception in thread "Thread-10" Exception in thread "Thread-11" Exception in thread "Thread-15" Exception in thread "Thread-9" Exception in thread "Thread-13" java.lang.ClassCircularityError: java/util/concurrent/ThreadLocalRandom
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.StripedBuffer.expandOrRetry(StripedBuffer.java:209)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.StripedBuffer.offer(StripedBuffer.java:149)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:1166)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:2066)
	at com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache.putIfAbsent(BoundedLocalCache.java:2003)
	at com.newrelic.weave.weavepackage.WeavePackageManager.getOptimizedWeavePackages(WeavePackageManager.java:606)
	at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:271)
	at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:261)
	at com.newrelic.agent.instrumentation.weaver.ClassWeaverService.newClassMatchVisitor(ClassWeaverService.java:455)
	at com.newrelic.agent.instrumentation.context.InstrumentationContext.match(InstrumentationContext.java:259)
	at com.newrelic.agent.instrumentation.context.InstrumentationContextClassMatcherHelper.isMatch(InstrumentationContextClassMatcherHelper.java:45)
	at com.newrelic.agent.instrumentation.context.ClassesMatcher$1.run(ClassesMatcher.java:55)
	at java.lang.Thread.run(Thread.java:748)

```
</details>
</p>

**Comment by Stephan202** [comment]
> @Stephan202 All tests are passing here. Do you prefer to update your original PR or just have us merge from here? Either works for me.

I noticed that in this repo you merge without squash-and-rebase, so then it's nicer to use the other pull request with the correct commit message. I rebased it just now :)

**Comment by tbradellis** [comment]
Using this branch to test a fix for the `ClassCircularityError`

**Pull request closed without merging**
