### PR TITLE
Java 15 support

### PR DESCRIPTION
**Pull request by tspring**
Adds support for Java 15 and upgrade ASM to version 8. Issue: https://github.com/newrelic/newrelic-java-agent/issues/53

### CODE REVIEW

**Review by XiXiaPdx — APPROVED** [review]
Nice!

**Review by breedx-nr — COMMENTED** [review]
There is a comment in a bunch of the weave code that caught my eye -- 
```
 * NOTE: If you are upgrading from org.ow2.asm:asm:8.0 / org.ow2.asm:asm-tree:8.0 make sure to double
 * check that this class hasn't changed between versions.
```
and that line changed due to the asm version upgrade.  

@tspring Did you do the legwork of looking at those classes to make sure they didn't change?

**Comment by tspring** [comment]
@breedx-nr I did, none of them have changed

**Comment by breedx-nr** [comment]
Great, thanks!

**Pull request merged**
