### PR TITLE
Add the missing delimiter in POSTGRES_DIALECT_PATTERN

### PR DESCRIPTION
**Pull request by malaki12003**
### Overview
I found a big issue in  r2dbc Postgresql instrumentation when it tries to Obfuscator the SQL queries. It seems the dilemma has been missed there.

### Checks

[x] Are your contributions backwards compatible with relevant frameworks and APIs?
[ ] Does your code contain any breaking changes? Please describe. 
[ ] Does your code introduce any new dependencies? Please describe.

### CODE REVIEW

**Comment by kford-newrelic** [comment]
@malaki12003 thanks for the PR!

We just missed the cutoff for our 7.11 release but we'll review this for the following release.

**Comment by malaki12003** [comment]
> @malaki12003 thanks for the PR!
> 
> We just missed the cutoff for our 7.11 release but we'll review this for the following release.

@kford-newrelic , I see, but it's going to be a hotfix and it would be better off including in 7.10.1. IMO, 7.12 is too late for such an important fix!

**Review by tbradellis — APPROVED** [review]
+lgtm

**Comment by tbradellis** [comment]
merged.

**Pull request merged**
